<div class="container" style="clear: both;margin-top:60px">
<?php
$pic = $images [0]->source;
?>
<div class="row12" style="margin-top: 40px"></div>
<div class="row">
	<div class="col-md-6">
		<img class="img-thumbnail" width="<?=$images[0]->width?>"
			height="<?=$images[0]->height?>"
			src='<?= str_replace('_s', '_n', $images[0]->source)?>' />
	</div>
	<div class="col-md-6 text-left">
		<div class="text-center"><?php echo $name;?></div>
	


  
<?php
// print_r($pictures);
foreach ( $comments as $k => $comment ) {
	?>

       <div class="col-md-12">
			<div class="col-md-12">
				<a href="#"> <img class="img-thumbnail"
					src='<?=$facebookurl.'/'.$comment->from->id?>/picture?type=small' />

					<a href="<?=$facebookurl.'/'.$comment->from->name?>"><?=$comment->from->name?></a>
			
			
				<span class="text-left"><?= $this->escapehtml($comment->message)?></span>
			</div>



		</div>
	
  <?php
}

?>
</div>
</div>