

<!--<div id="myCarousel" class="carousel slide" data-ride="carousel">-->



    <div class="row12">
        <?php
        function getFacebookImageFromURL($url)
        {
            $headers = get_headers($url, 1);
            if (isset($headers['Location']))
            {
                return $headers['Location'];
            }
        }
        //print_r($pictures);
        foreach ($posts as $k => $post) {
           if(!property_exists($post, 'message')) {
               $post->message = '';
           }
            if(!property_exists($post, 'description')) {
                $post->description = '';
            }
            ///picture?type=large
            ?>

            <div class="col-md-12" style="margin-top:10px;border:1px solid #c0c0c0">
                <?php if($post->type ==='photo'){
                     $url = $facebookurl.'/'. $post->object_id.'/picture?type=normal';

                    ?>
                <a href="/Fpage/Albums/pictureDetails/<?= $post->object_id ?>">
                    <img style="float: left;margin:5px"
                         src='<?= getFacebookImageFromURL($url)?>'>
                </a>

                   <?php
                } else


                    if ($post->type ==='video'){

                        ?>
                         <a href="<?=$post->link?>" target="_blank"><?=$post->name?></a>
                        <embed src="<?= str_replace('autoplay=1','autoplay=0',$post->source)?>"></embed>
                    <?php
                    }
                    ?>
                <p class="text-left" style = "margin:5px;padding:5px;line-height:1.5em;text-indent:2em" >
                    <?=  $post->message.'<br/>'.$post->description?>
                </p>
            </div>

        <?php

        }

        ?>
    </div>
    <!-- Carousel nav
    <a class="carousel-control left" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
    -->
<!--</div>-->
  